CREATE type card_vote_types AS ENUM ('great', 'good', 'bad', 'shit');

create table card_votes (
  id bigint generated by default as identity primary key, 
  vote_type card_vote_types not null,
  created_at timestampt with time zone default current_timestamp, 
  user_id uuid references auth.users(id) on delete cascade,
  title text not null
) 

create table profiles (
  id uuid references auth.users(id) primary key,
  first_name varchar(50), 
  last_name varchar(50), 
  email varchar(50) unique not null, 
  job varchar(50),
  phone varchar(50),
  bio text, 
  website varchar(50), 
  github varchar(50)
);  

create table profile_skills (
  id bigint generated by default as identity primary key, 
  created_at timestamp with time zone default current_timestamp, 
  profile_id uuid references profiles(id) not null, 
  skill_tag_id int references skill_tags(id) not null
)

create table skill_tags (
  id int generated by default as identity primary key, 
  name varchar(50) unique not null, 
  created_at timestamp with time zone default current_timestamp
)




